#!/usr/bin/env bash

set -e
set -x

TUBESHIFT_ROOT="$(dirname $0)"
DIST_FILE="${TUBESHIFT_ROOT}/tubeshift.chrome.zip"

cd "$TUBESHIFT_ROOT"

rm -f "${DIST_FILE}"

zip -r "${DIST_FILE}" \
    manifest.json *.txt \
    *.html *.css *.js \
    icons/*.png icons/*.svg icons/*.txt \
    img/*.png \
    platform/*.js \
    js/*.js
